CREATE DATABASE IF NOT EXISTS simifm CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE simifm;

CREATE TABLE IF NOT EXISTS wa_template (
 id INT UNSIGNED NOT NULL AUTO_INCREMENT,
 template_code VARCHAR(150) NOT NULL,
 template_name VARCHAR(150) NOT NULL,
 category VARCHAR(50) DEFAULT NULL,
 language VARCHAR(20) DEFAULT 'id',
 body TEXT NOT NULL,
 variables TEXT DEFAULT NULL,
 status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
 created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(id), UNIQUE KEY uk_template_code(template_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS wa_outbox (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 destination VARCHAR(30) NOT NULL,
 template_code VARCHAR(150) NOT NULL,
 payload LONGTEXT DEFAULT NULL,
 status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
 attempts INT UNSIGNED NOT NULL DEFAULT 0,
 msgid VARCHAR(150) DEFAULT NULL,
 response LONGTEXT DEFAULT NULL,
 error_message TEXT DEFAULT NULL,
 scheduled_at DATETIME DEFAULT NULL,
 sent_at DATETIME DEFAULT NULL,
 created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(id), KEY idx_status(status), KEY idx_schedule(scheduled_at), KEY idx_msgid(msgid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS simifm_user (
 id INT UNSIGNED NOT NULL AUTO_INCREMENT,
 username VARCHAR(100) NOT NULL,
 password VARCHAR(255) NOT NULL,
 nama VARCHAR(150) DEFAULT NULL,
 status ENUM('aktif','nonaktif') NOT NULL DEFAULT 'aktif',
 created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(id), UNIQUE KEY uk_username(username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;